### ISSUE TITLE
Unbounded memory usage

### ISSUE THREAD

**Issue by maxcountryman** [yaorg/node-measured#24] opened 2017-02-22 22:44 UTC
I'm noticing issues where Node processes consuming histograms (and surprisingly) meters are growing memory in a linear, unbounded fashion. Removing `measured` fixes this issue. I'm not very surprised that histograms are memory-hungry given they're backed by a binary heap, I am much more surprised the meters seem to be as well.

Is this something you've encountered before?

**Comment by felixge** [comment] 2017-02-23 08:59
@maxcountryman I never observed this when I still used the library. The code was all written to avoid unbound memory growth.

**Comment by maxcountryman** [comment] 2017-02-23 13:59
Perhaps this has something to do with the event emitters attached to these objects?

I implemented my own structures and observed no memory issues whatsoever.

**Comment by maxcountryman** [comment] 2017-03-01 20:28
I believe the source of these leaks is `setInterval` and perhaps the usage of `unref`. It's a fairly catastrophic leak in environments where a lot of data is being thrown at meters (it's taken down my ec2 instances several times now). I'm not really sure what the best "fix" for this is.

**Comment by jondot** [comment] 2017-07-24 09:47
This is important enough to put a notice in the README. We've taken this as a dependency to avoid writing our own data structures and then as a result to be having to write code for handling unbounded memory edge cases, but looks like it also has these.

**Comment by mantoni** [comment] 2017-07-24 11:40
I use this library in production code for several years with node 0.12, 4 and 6. We constantly monitor our process  memory and I can NOT confirm that there is a leak. To anyone reading this thread, please trace the source of your leaks using a profiler and point us in the right direction. Should there be a memory leak, I'd instantly merge a PR with a fix.

**Comment by maxcountryman** [comment] 2017-07-24 18:23
IIRC the problem turned out to be the binary heap that underpins much of this library. This structure eventually causes an OOM error, especially when fed a lot of data quickly.

Coda Hale's [metrics library](https://github.com/dropwizard/metrics) is a much better example of how to do similar things without binary heaps.

I personally stopped using this library as soon as I discovered the problem and so I don't have a vested interest in fixing it. So I'll leave this note here and let the authors decide how they'd like to proceed.

**Comment by jondot** [comment] 2017-07-26 07:19
Update: the thing is, that if you use meters (which use a timer to periodically aggregate the data), and then you swap them periodically to avoid a meter going out of range - you get dangling timers.

In addition if you use many meters, let's say 100 in an app, then you have 100 timers running - does that affect performance?

**Comment by eugef** [comment] 2018-04-26 08:39
Any update on this issue, does anyone run this library with Node 8 or 10?

**Comment by fieldju** [comment] 2018-05-04 21:04
@eugef i'm in the process of writing some Gatling performance tests to validate or invalidate this.

**Comment by fieldju** [comment] 2018-05-23 19:39
@jondot, @maxcountryman 

Can you help me understand this issue better so I can do some TDD / reproduce the issue and verify that the issue has been resolved.

```I believe the source of these leaks is setInterval and perhaps the usage of unref.```

```Update: the thing is, that if you use meters (which use a timer to periodically aggregate the data), and then you swap them periodically to avoid a meter going out of range - you get dangling timers.```

I just want to either write a test that fails so I can do TDD, or if that isn't possible just knowing how to reproduce would be nice so I can manually verify a fix.

**Comment by fieldju** [comment] 2018-06-02 19:36
Closing this issue as I can't reproduce it, feel free to re-open with steps to reproduce.

**Closed by fieldju** 2018-06-02 19:36 UTC
Labels: Steps to reproduce wanted.

**Comment by fieldju** [comment] 2018-06-06 17:30
I know I already closed this issue. Just incase anyone finds themselves here.

My suspicion based on some of the comments above. Is that Meters where being created regularly and there lifecycles where not being managed properly.

When a Meter is created you must call Meter.end() when you are done with it. The end method clears the interval which would allow the garbage collector to fully destroy the object.
